spring:
  application:
    name: order
  datasource:
    url: 'jdbc:postgresql://localhost:5432/deliveryman'
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    database-change-log-table: order_database_change_log
    database-change-log-lock-table: order_database_change_log_lock


server:
  port: 0


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
